# Generated by Django 2.1.9 on 2020-05-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategoryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubCategory_ID', models.CharField(max_length=100)),
                ('SubCategory_Name', models.CharField(max_length=100)),
                ('SubCategory_Image', models.ImageField(upload_to='subcategoryimage/')),
            ],
            options={
                'db_table': 'SubCategoryData',
            },
        ),
    ]
