# Generated by Django 2.1.9 on 2020-05-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_subcategorydata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorydata',
            name='id',
        ),
        migrations.RemoveField(
            model_name='subcategorydata',
            name='id',
        ),
        migrations.AddField(
            model_name='subcategorydata',
            name='Category_ID',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categorydata',
            name='Category_ID',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subcategorydata',
            name='SubCategory_ID',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
