# Generated by Django 2.1.1 on 2020-05-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200523_0119'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessData',
            fields=[
                ('Business_ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Category_ID', models.CharField(max_length=100)),
                ('Business_Name', models.CharField(max_length=500)),
                ('Owner_Name', models.CharField(max_length=200)),
                ('Mobile', models.CharField(max_length=15)),
                ('Email', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=50)),
                ('Status', models.CharField(default='Active', max_length=50)),
            ],
            options={
                'db_table': 'BusinessData',
            },
        ),
    ]
