# Generated by Django 2.1.1 on 2020-05-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_businessdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdata',
            name='Business_Adhaar',
            field=models.ImageField(default='NA', upload_to='businessadhaar/'),
        ),
        migrations.AddField(
            model_name='businessdata',
            name='Business_Logo',
            field=models.ImageField(default='NA', upload_to='businesslogo/'),
        ),
        migrations.AddField(
            model_name='businessdata',
            name='SubCategory_ID',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
