# Generated by Django 2.1.1 on 2020-05-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200523_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdata',
            name='Business_Adhaar',
            field=models.ImageField(blank=True, upload_to='businessadhaar/'),
        ),
        migrations.AlterField(
            model_name='businessdata',
            name='Business_Logo',
            field=models.ImageField(blank=True, upload_to='businesslogo/'),
        ),
    ]
