# Generated by Django 2.1.1 on 2020-05-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200524_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdata',
            name='Business_Adhaar',
            field=models.ImageField(upload_to='badhaar/'),
        ),
        migrations.AlterField(
            model_name='businessdata',
            name='Business_Logo',
            field=models.ImageField(upload_to='blogo/'),
        ),
    ]
