# Generated by Django 2.1.1 on 2020-05-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200524_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesData',
            fields=[
                ('Service_ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Business_ID', models.CharField(max_length=100)),
                ('Service_Name', models.CharField(max_length=200)),
                ('Service_Description', models.CharField(max_length=2000)),
                ('Service_Price', models.CharField(max_length=100)),
                ('Status', models.CharField(default='Active', max_length=50)),
            ],
            options={
                'db_table': 'ServicesData',
            },
        ),
        migrations.CreateModel(
            name='ServicesImagesData',
            fields=[
                ('Service_ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Service_Image', models.ImageField(upload_to='servicesimages/')),
            ],
            options={
                'db_table': 'ServicesImagesData',
            },
        ),
    ]
