# Generated by Django 2.1.1 on 2020-05-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200525_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdata',
            name='Business_Address',
            field=models.CharField(default='Not Availiable', max_length=500),
        ),
        migrations.AddField(
            model_name='businessdata',
            name='Business_City',
            field=models.CharField(default='Not Availiable', max_length=100),
        ),
        migrations.AddField(
            model_name='businessdata',
            name='Business_State',
            field=models.CharField(default='Not Availiable', max_length=100),
        ),
    ]
