# Generated by Django 2.1.1 on 2020-05-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200527_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessdata',
            old_name='Category_ID',
            new_name='Business_Email',
        ),
        migrations.RenameField(
            model_name='businessdata',
            old_name='Mobile',
            new_name='Business_Mobile',
        ),
        migrations.RenameField(
            model_name='businessdata',
            old_name='Password',
            new_name='Business_Password',
        ),
        migrations.RenameField(
            model_name='businessdata',
            old_name='Email',
            new_name='Category_Name',
        ),
        migrations.RenameField(
            model_name='businessdata',
            old_name='SubCategory_ID',
            new_name='SubCategory_Name',
        ),
        migrations.RemoveField(
            model_name='businessdata',
            name='Business_Adhaar',
        ),
        migrations.RemoveField(
            model_name='businessdata',
            name='Owner_Name',
        ),
        migrations.AddField(
            model_name='businessdata',
            name='Business_Decription',
            field=models.CharField(default='Not Availiable', max_length=1000),
        ),
        migrations.AddField(
            model_name='businessdata',
            name='Business_Website',
            field=models.CharField(default='Not Availiable', max_length=100),
        ),
        migrations.AddField(
            model_name='businessdata',
            name='Owner_FName',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AddField(
            model_name='businessdata',
            name='Owner_LName',
            field=models.CharField(default='NA', max_length=200),
        ),
    ]
