# Generated by Django 2.1.1 on 2020-05-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200528_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('User_ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('User_FName', models.CharField(max_length=100)),
                ('User_LName', models.CharField(max_length=100)),
                ('User_Mobile', models.CharField(max_length=100)),
                ('User_Email', models.CharField(max_length=100)),
                ('User_Password', models.CharField(max_length=100)),
                ('Verify_Status', models.CharField(default='Unverified', max_length=100)),
                ('Verify_Code', models.CharField(max_length=100)),
                ('Account_Status', models.CharField(default='Active', max_length=100)),
            ],
            options={
                'db_table': 'UserData',
            },
        ),
    ]
