# Generated by Django 2.1.1 on 2020-05-31 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_userdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='Verify_Code',
        ),
    ]
