# Generated by Django 2.1.1 on 2020-06-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_userdata_verify_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessdata',
            old_name='Business_Email',
            new_name='Contact_Email',
        ),
        migrations.RemoveField(
            model_name='businessdata',
            name='Business_Mobile',
        ),
        migrations.RemoveField(
            model_name='businessdata',
            name='Business_Password',
        ),
        migrations.RemoveField(
            model_name='businessdata',
            name='Owner_FName',
        ),
        migrations.RemoveField(
            model_name='businessdata',
            name='Owner_LName',
        ),
        migrations.AddField(
            model_name='businessdata',
            name='Contact_Name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessdata',
            name='Contact_Number',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessdata',
            name='User_ID',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
