# Generated by Django 2.1.9 on 2020-06-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20200601_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallData',
            fields=[
                ('Call_ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Business_ID', models.CharField(max_length=100)),
                ('Service_ID', models.CharField(max_length=100)),
                ('Customer_Name', models.CharField(max_length=100)),
                ('Customer_Number', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'CallData',
            },
        ),
    ]
