# Generated by Django 2.1.9 on 2020-06-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_calldata_service_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostData',
            fields=[
                ('Post_Date', models.CharField(default='03/06/2020', max_length=50)),
                ('Post_ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Business_ID', models.CharField(max_length=100)),
                ('User_ID', models.CharField(max_length=100)),
                ('Post_Title', models.CharField(max_length=100)),
                ('Post_Description', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'PostData',
            },
        ),
    ]
