# Generated by Django 2.1.9 on 2020-06-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_postdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServicesImagesData',
        ),
        migrations.RemoveField(
            model_name='servicesdata',
            name='Service_Description',
        ),
        migrations.RemoveField(
            model_name='servicesdata',
            name='Service_Price',
        ),
        migrations.AlterField(
            model_name='postdata',
            name='Post_Date',
            field=models.CharField(default='09/06/2020', max_length=50),
        ),
    ]
