# Generated by Django 2.1.9 on 2020-06-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20200609_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSocialMediaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Business_ID', models.CharField(max_length=100)),
                ('Facebook', models.CharField(max_length=200)),
                ('Instagram', models.CharField(max_length=200)),
                ('Twitter', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'BusinessSocialMediaData',
            },
        ),
    ]
