# Generated by Django 2.1.9 on 2020-06-10 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_businesssocialmediadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessMapsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Business_ID', models.CharField(max_length=100)),
                ('Maps', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'BusinessMapsData',
            },
        ),
        migrations.AlterField(
            model_name='postdata',
            name='Post_Date',
            field=models.CharField(default='10/06/2020', max_length=50),
        ),
    ]
