# Generated by Django 2.1.9 on 2020-06-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_businessdata_business_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessImagesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Business_ID', models.CharField(max_length=100)),
                ('Image', models.FileField(upload_to='BusinessImageGallery/')),
            ],
            options={
                'db_table': 'BusinessImagesData',
            },
        ),
        migrations.AlterField(
            model_name='businesslogodata',
            name='Business_Logo',
            field=models.FileField(upload_to='logo/'),
        ),
    ]
