# Generated by Django 2.1.9 on 2020-06-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20200610_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdata',
            name='Join_Date',
            field=models.CharField(default='10/06/2020', max_length=50),
        ),
        migrations.AddField(
            model_name='userdata',
            name='Join_Date',
            field=models.CharField(default='10/06/2020', max_length=50),
        ),
    ]
