# Generated by Django 2.1.9 on 2020-06-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20200610_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdata',
            name='VerifyBadge',
            field=models.CharField(default='Unverified', max_length=50),
        ),
    ]
