# Generated by Django 2.1.9 on 2020-06-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_businessdata_verifybadge'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessTopBannerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Business_ID', models.CharField(max_length=100)),
                ('Banner', models.FileField(upload_to='BusinessTopBanner/')),
            ],
            options={
                'db_table': 'BusinessTopBannerData',
            },
        ),
    ]
