# Generated by Django 2.1.9 on 2020-06-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_businesstopbannerdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLeadsData',
            fields=[
                ('User_ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Post_ID', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'UserLeadsData',
            },
        ),
    ]
