# Generated by Django 2.1.9 on 2020-06-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_userleadsdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userleadsdata',
            name='Post_ID',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userleadsdata',
            name='User_ID',
            field=models.CharField(max_length=100),
        ),
    ]
