# Generated by Django 2.1.9 on 2020-06-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20200610_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAdBannerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Business_ID', models.CharField(max_length=100)),
                ('Banner', models.FileField(upload_to='BusinessAdBanner/')),
            ],
            options={
                'db_table': 'BusinessAdBannerData',
            },
        ),
        migrations.AlterField(
            model_name='businessdata',
            name='Join_Date',
            field=models.CharField(default='12/06/2020', max_length=50),
        ),
        migrations.AlterField(
            model_name='postdata',
            name='Post_Date',
            field=models.CharField(default='12/06/2020', max_length=50),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='Join_Date',
            field=models.CharField(default='12/06/2020', max_length=50),
        ),
    ]
