# Generated by Django 2.1.9 on 2020-06-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20200612_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessReviewData',
            fields=[
                ('Review_ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Business_ID', models.CharField(max_length=100)),
                ('User_ID', models.CharField(default='Unknown', max_length=100)),
                ('Review', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'BusinessReviewData',
            },
        ),
        migrations.CreateModel(
            name='PlanData',
            fields=[
                ('Plan_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('BusinessListing', models.CharField(max_length=10)),
                ('Ads', models.CharField(max_length=10)),
                ('Map', models.CharField(max_length=10)),
                ('Contact', models.CharField(max_length=10)),
                ('Logo', models.CharField(max_length=10)),
                ('AdBanner', models.CharField(max_length=10)),
                ('URL', models.CharField(max_length=10)),
                ('SocialMedia', models.CharField(max_length=10)),
                ('Product', models.CharField(max_length=10)),
                ('BusinessHours', models.CharField(max_length=10)),
                ('ImageGallery', models.CharField(max_length=10)),
                ('TopBanner', models.CharField(max_length=10)),
                ('Verified', models.CharField(max_length=10)),
                ('UserChat', models.CharField(max_length=10)),
                ('Review', models.CharField(max_length=10)),
                ('Blog', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'PlanData',
            },
        ),
    ]
