# Generated by Django 2.1.9 on 2020-06-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_businessreviewdata_plandata'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessreviewdata',
            name='Rating',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businessdata',
            name='Join_Date',
            field=models.CharField(default='13/06/2020', max_length=50),
        ),
        migrations.AlterField(
            model_name='businessreviewdata',
            name='Review',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='postdata',
            name='Post_Date',
            field=models.CharField(default='13/06/2020', max_length=50),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='Join_Date',
            field=models.CharField(default='13/06/2020', max_length=50),
        ),
    ]
