# Generated by Django 2.1.9 on 2020-06-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20200613_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSubscribeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plan_ID', models.CharField(max_length=100)),
                ('User_ID', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'PlanSubscribeData',
            },
        ),
    ]
