# Generated by Django 2.1.9 on 2020-06-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_plansubscribedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='plandata',
            name='Lead',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
