# Generated by Django 2.1.9 on 2020-06-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_plandata_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentData',
            fields=[
                ('Pay_ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Plan_ID', models.CharField(max_length=100)),
                ('User_ID', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'PaymentData',
            },
        ),
    ]
