# Generated by Django 2.1.9 on 2020-06-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_paymentdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentData2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pay_ID', models.CharField(max_length=100)),
                ('CURRENCY', models.CharField(blank=True, default='None', max_length=100)),
                ('GATEWAYNAME', models.CharField(blank=True, default='None', max_length=100)),
                ('RESPMSG', models.CharField(blank=True, default='None', max_length=1000)),
                ('BANKNAME', models.CharField(blank=True, default='None', max_length=100)),
                ('PAYMENTMODE', models.CharField(blank=True, default='None', max_length=100)),
                ('RESPCODE', models.CharField(blank=True, default='None', max_length=100)),
                ('TXNID', models.CharField(blank=True, default='None', max_length=100)),
                ('TXNAMOUNT', models.CharField(blank=True, default='None', max_length=100)),
                ('STATUS', models.CharField(blank=True, default='None', max_length=100)),
                ('BANKTXNID', models.CharField(blank=True, default='None', max_length=100)),
                ('TXNDATE', models.CharField(blank=True, default='None', max_length=100)),
                ('CHECKSUMHASH', models.CharField(blank=True, default='None', max_length=100)),
            ],
            options={
                'db_table': 'PaymentData2',
            },
        ),
    ]
