# Generated by Django 2.1.9 on 2020-06-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_paymentdata2'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogData',
            fields=[
                ('Blog_Date', models.CharField(default='15/06/2020', max_length=100)),
                ('Blog_ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('User_ID', models.CharField(default='Admin', max_length=100)),
                ('Title', models.CharField(max_length=100)),
                ('Body', models.CharField(max_length=1000)),
                ('Image', models.FileField(upload_to='BlogImages/')),
            ],
            options={
                'db_table': 'BlogData',
            },
        ),
        migrations.CreateModel(
            name='BusinessReviewReplyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Review_ID', models.CharField(max_length=100)),
                ('Reply', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'BusinessReviewReplyData',
            },
        ),
        migrations.AddField(
            model_name='userleadsdata',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businessdata',
            name='Join_Date',
            field=models.CharField(default='15/06/2020', max_length=50),
        ),
        migrations.AlterField(
            model_name='postdata',
            name='Post_Date',
            field=models.CharField(default='15/06/2020', max_length=50),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='Join_Date',
            field=models.CharField(default='15/06/2020', max_length=50),
        ),
        migrations.AlterField(
            model_name='userleadsdata',
            name='Post_ID',
            field=models.CharField(max_length=100),
        ),
    ]
