# Generated by Django 2.1.9 on 2020-06-16 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20200615_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifiedData',
            fields=[
                ('AD_ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('AD_Date', models.CharField(default='16/06/2020', max_length=50)),
                ('City', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=500)),
                ('Images', models.FileField(upload_to='classifiedimages/')),
            ],
            options={
                'db_table': 'ClassifiedData',
            },
        ),
        migrations.AlterField(
            model_name='blogdata',
            name='Blog_Date',
            field=models.CharField(default='16/06/2020', max_length=100),
        ),
        migrations.AlterField(
            model_name='businessdata',
            name='Join_Date',
            field=models.CharField(default='16/06/2020', max_length=50),
        ),
        migrations.AlterField(
            model_name='postdata',
            name='Post_Date',
            field=models.CharField(default='16/06/2020', max_length=50),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='Join_Date',
            field=models.CharField(default='16/06/2020', max_length=50),
        ),
    ]
