# Generated by Django 2.1.9 on 2020-06-16 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20200616_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifieddata',
            name='AD_Category',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
