# Generated by Django 2.1.9 on 2020-06-16 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_classifieddata_ad_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifiedImagesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AD_ID', models.CharField(max_length=100)),
                ('Images', models.FileField(upload_to='classifiedimages/')),
            ],
            options={
                'db_table': 'ClassifiedImagesData',
            },
        ),
        migrations.RemoveField(
            model_name='classifieddata',
            name='Images',
        ),
    ]
