# Generated by Django 2.1.9 on 2020-06-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_auto_20200617_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='calldata',
            name='Customer_Message',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
