# Generated by Django 2.1.9 on 2020-06-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_calldata_customer_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifieddata',
            name='Price',
            field=models.CharField(default='100', max_length=50),
        ),
    ]
