from django.contrib import admin
from django.urls import path
from app.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',blog),
    path('cart/',cart),
    path('category/',category),
    path('checkout/',checkout),
    path('confirmation/',confirmation),
    path('contact/',contact),
    path('elements/',elements),
    path('index/',index),
    path('login/',login),
    path('registration/',registration),
    path('singleblog/',singleblog),
    path('singleproduct/',singleproduct),
    path('tracking/',tracking),
    path('navbar/',adminnavbar),
    path('adminindex/',adminindex),
    path('sidebar/',adminsidebar),
    path('basicelements/',adminbasicelements),
    path('basictable/',adminbasictable),
    path('blankpage/',adminblankpage),
    path('buttons/',adminbuttons),
    path('chartjs/',adminchartjs),
    path('dropdowns/',admindropdowns),
    path('error404/',adminerror404),
    path('error500/',adminerror500),
    path('fontawesome/',adminfontawesome),
    path('adminlogin/',adminlogin),
    path('adminregister/',adminregister),
    path('typography/',admintypography),
    path('adminlogincheck/',adminlogincheck),
    path('defaultcategorieslist/',defaultcategorieslist),
    path('addsubcategory/',addsubcategory),
    path('postadd/',postadd),
    path('sellads/',sellads),
    path('rentads/',rentads),
]
